local locales = {
	["enUS"] = {
		["Always display CD icons at full opacity (ReloadUI is needed)"] = "Always display CD icons at full opacity (ReloadUI is needed)",
		["Click on icon to enable/disable tracking"] = "Click on icon to enable/disable tracking",
		Copy = "Copy",
		["Copy other profile to current profile:"] = "Copy other profile to current profile:",
		["Current profile: [%s]"] = "Current profile: [%s]",
		["Data from '%s' has been successfully copied to '%s'"] = "Data from '%s' has been successfully copied to '%s'",
		Delete = "Delete",
		["Delete profile:"] = "Delete profile:",
		["Disable test mode"] = "Disable test mode",
		["Enable test mode (need at least one visible nameplate)"] = "Enable test mode (need at least one visible nameplate)",
		General = "General",
		["Icon size"] = "Icon size",
		["Icon X-coord offset"] = "Icon X-coord offset",
		["Icon Y-coord offset"] = "Icon Y-coord offset",
		MISC = "Misc",
		["New spell has been added: %s"] = "New spell has been added: %s",
		["Options are not available in combat!"] = "Options are not available in combat!",
		Profiles = "Profiles",
		["Profile '%s' has been successfully deleted"] = "Profile '%s' has been successfully deleted",
		["Show border around interrupts"] = "Show border around interrupts",
		["Show border around trinkets"] = "Show border around trinkets",
		["Unknown spell: %s"] = "Unknown spell: %s",
		["Value must be a number"] = "Value must be a number",
		["Font:"] = "Font:",
		["Standard spells"] = "Standard spells",
		["User-defined spells"] = "User-defined spells",
	},
	["deDE"] = {
		["Always display CD icons at full opacity (ReloadUI is needed)"] = "CD-Symbole immer mit voller Deckkraft anzeigen (UI neu laden erf.)",
		["Click on icon to enable/disable tracking"] = "Klicke auf das Symbol, um die Verfolgung ein-/auszuschalten",
		Copy = "Kopieren",
		["Copy other profile to current profile:"] = "Kopiere ein anderes Profil zu dem aktuellen:",
		["Current profile: [%s]"] = "Aktuelles Profil: [%s]",
		["Data from '%s' has been successfully copied to '%s'"] = "Daten von '%s' wurden erfolgreich zu '%s' kopiert.",
		Delete = "Löschen",
		["Delete profile:"] = "Profil löschen:",
		["Disable test mode"] = "Testmodus deaktivieren",
		["Enable test mode (need at least one visible nameplate)"] = "Testmodus aktivieren\r\n(es muss mindestens eine Namensplakette sichtbar sein)", -- Needs review
		["Font:"] = "Schriftart:",
		General = "Allgemein",
		["Icon size"] = "Symbolgröße ",
		["Icon X-coord offset"] = "X-Position des Symbols",
		["Icon Y-coord offset"] = "Y-Position des Symbols",
		MISC = "Verschiedenes",
		["New spell has been added: %s"] = "Ein neuer Zauber wurde hinzugefügt: %s",
		["Options are not available in combat!"] = "Einstellungen sind nicht im Kampf verfügbar",
		Profiles = "Profile",
		["Profile '%s' has been successfully deleted"] = "Profil '%s' wurde erfolgreich gelöscht.",
		["Show border around interrupts"] = "Rahmen um Unterbrechungen anzeigen",
		["Show border around trinkets"] = "Rahmen um Schmuckstücke anzeigen",
		["Unknown spell: %s"] = "Unbekannter Zauber: %s",
		["Value must be a number"] = "Der Wert muss eine Zahl sein.",
	},
	["ruRU"] = {
		["Always display CD icons at full opacity (ReloadUI is needed)"] = "Иконки заклинаний всегда полностью непрозрачны\r\n(Необходима перезагрузка интерфейса)",
		["Click on icon to enable/disable tracking"] = "Нажмите на иконку чтобы вкл/выкл отслеживание",
		Copy = "Скопировать",
		["Copy other profile to current profile:"] = "Скопировать другой профиль в текущий:",
		["Current profile: [%s]"] = "Текущий профиль: [%s]",
		["Data from '%s' has been successfully copied to '%s'"] = "Профиль '%s' успешно скопирован в профиль '%s'",
		Delete = "Удалить",
		["Delete profile:"] = "Удалить профиль:",
		["Disable test mode"] = "Выключить тест",
		["Enable test mode (need at least one visible nameplate)"] = "Включить тест (нужен хотя бы 1 видимый хп бар)",
		General = "Общее",
		["Icon size"] = "Размер иконок",
		["Icon X-coord offset"] = "Смещение иконок по X",
		["Icon Y-coord offset"] = "Смещение иконок по Y",
		MISC = "Другое",
		["New spell has been added: %s"] = "Добавлено новое заклинание: %s",
		["Options are not available in combat!"] = "Настройки недоступны, пока идет бой!",
		Profiles = "Профили",
		["Profile '%s' has been successfully deleted"] = "Профиль '%s' успешно удален",
		["Show border around interrupts"] = "Показывать контур вокруг прерываний",
		["Show border around trinkets"] = "Показывать контур вокруг тринкетов",
		["Unknown spell: %s"] = "Неизвестное заклинание: %s",
		["Value must be a number"] = "Значение должно быть числом",
		["Font:"] = "Шрифт:",
	},
	["esMX"] = {
		["Always display CD icons at full opacity (ReloadUI is needed)"] = "Mostrar siempre iconos con opacidad completa (Se requiere recargar UI)", -- Needs review
		["Click on icon to enable/disable tracking"] = "Click sobre el icono para habilitar/desactivar el hechizo.", -- Needs review
		Copy = "Copiar", -- Needs review
		["Copy other profile to current profile:"] = "Copiar otro perfil al actual:", -- Needs review
		["Current profile: [%s]"] = "Perfil actual: [%s]", -- Needs review
		["Data from '%s' has been successfully copied to '%s'"] = "Los datos de '%s' se han copiado a '%s'", -- Needs review
		Delete = "Borrar", -- Needs review
		["Delete profile:"] = "Borrar perfil:", -- Needs review
		["Disable test mode"] = "Desactivar modo de prueba.", -- Needs review
		["Enable test mode (need at least one visible nameplate)"] = "Habilitar modo de prueba\r\n(se necesitar tener una placa de nombre visible).", -- Needs review
		General = "General", -- Needs review
		["Icon size"] = "Tamaño del icono", -- Needs review
		["Icon X-coord offset"] = "Coordenada X de los iconos", -- Needs review
		["Icon Y-coord offset"] = "Coordenada Y de los iconos", -- Needs review
		MISC = "Varios ", -- Needs review
		["New spell has been added: %s"] = "Se ha agregado un nuevo hechizo: %s", -- Needs review
		["Options are not available in combat!"] = "Configuración no disponible durante el combate!", -- Needs review
		Profiles = "Perfiles", -- Needs review
		["Profile '%s' has been successfully deleted"] = "El perfil '%s' ha sido eliminado.", -- Needs review
		["Show border around interrupts"] = "Mostrar borde en interrupciones ", -- Needs review
		["Show border around trinkets"] = "Mostrar borde en albalorios", -- Needs review
		["Unknown spell: %s"] = "Hechizo desconocido: %s", -- Needs review
		["Value must be a number"] = "El valor debe ser un numero", -- Needs review
		["Font:"] = "Font:",
	},
	["frFR"] = {
		["Always display CD icons at full opacity (ReloadUI is needed)"] = "Always display CD icons at full opacity (ReloadUI is needed)", -- Requires localization
		["Click on icon to enable/disable tracking"] = "Cliquez sur l'icone pour activer/désactiver le suivi",
		Copy = "Copier",
		["Copy other profile to current profile:"] = "Copie un profile vers le profile courant",
		["Current profile: [%s]"] = "Profile courrant : [%s]",
		["Data from '%s' has been successfully copied to '%s'"] = "Les données de '%s' ont été copiées vers '%s'",
		Delete = "Effacer",
		["Delete profile:"] = "Effacer le profile :",
		["Disable test mode"] = "Éteindre le mode test",
		["Enable test mode (need at least one visible nameplate)"] = "Allumer le mode test ( nécessite au moins une étiquette de nom visible)",
		General = "Général",
		["Icon size"] = "Taille de l'icone",
		["Icon X-coord offset"] = "Icon X-coord offset", -- Needs review
		["Icon Y-coord offset"] = "Icon Y-coord offset", -- Needs review
		MISC = "Divers",
		["New spell has been added: %s"] = "Un nouveau sort a été ajouté : %s",
		["Options are not available in combat!"] = "Les options sont indisponibles durant un combat",
		Profiles = "Profiles",
		["Profile '%s' has been successfully deleted"] = "Le profile '%s' a été effacé.",
		["Show border around interrupts"] = "Show border around interrupts", -- Requires localization
		["Show border around trinkets"] = "Show border around trinkets", -- Requires localization
		["Unknown spell: %s"] = "Sort inconnu : %s",
		["Value must be a number"] = "La valeur doit être un nombre",
		["Font:"] = "Font:",
	},
	["esES"] = {
		["Always display CD icons at full opacity (ReloadUI is needed)"] = "Always display CD icons at full opacity (ReloadUI is needed)", -- Requires localization
		["Click on icon to enable/disable tracking"] = "Haz click en el icono para activar/desactivar seguimiento", -- Needs review
		Copy = "Copiar", -- Needs review
		["Copy other profile to current profile:"] = "Copiar otro perfil al perfil actual:", -- Needs review
		["Current profile: [%s]"] = "Perfil actual: [%s]", -- Needs review
		["Data from '%s' has been successfully copied to '%s'"] = "Los datos de '% s' han sido copiados correctamente a '% s'", -- Needs review
		Delete = "Borrar", -- Needs review
		["Delete profile:"] = "Borrar perfil:", -- Needs review
		["Disable test mode"] = "Desactivar Modo Test", -- Needs review
		["Enable test mode (need at least one visible nameplate)"] = "Modo test Activado\r\n(necesitas por lo menos un nameplate visible)", -- Needs review
		General = "General", -- Needs review
		["Icon size"] = "Tamaño del icono", -- Needs review
		["Icon X-coord offset"] = "Compensacion de coordenada X del icono", -- Needs review
		["Icon Y-coord offset"] = "Compensacion de coordenada Y del icono", -- Needs review
		MISC = "Misc", -- Needs review
		["New spell has been added: %s"] = "Añadido un nuevo hechizo: %s", -- Needs review
		["Options are not available in combat!"] = "Las opciones no estan disponibles en combate!", -- Needs review
		Profiles = "Perfiles", -- Needs review
		["Profile '%s' has been successfully deleted"] = "Perfil \"%s\" ha sido borrado con exito", -- Needs review
		["Show border around interrupts"] = "Show border around interrupts", -- Requires localization
		["Show border around trinkets"] = "Show border around trinkets", -- Requires localization
		["Unknown spell: %s"] = "Hechizo desconocido: %s", -- Needs review
		["Value must be a number"] = "El valor debe ser numerico", -- Needs review
		["Font:"] = "Font:",
	},
	["koKR"] = {
		["Always display CD icons at full opacity (ReloadUI is needed)"] = "Always display CD icons at full opacity (ReloadUI is needed)", -- Requires localization
		["Click on icon to enable/disable tracking"] = "아이콘을 클릭하여 추적을 활성화/비활성화 하십시오", -- Needs review
		Copy = "복사", -- Needs review
		["Copy other profile to current profile:"] = "다른 프로필을 현재 프로필에 복사", -- Needs review
		["Current profile: [%s]"] = "현재 프로필: [%s]", -- Needs review
		["Data from '%s' has been successfully copied to '%s'"] = "'%s' 의 데이터가 성공적으로 '%s'에 복사되었습니다.", -- Needs review
		Delete = "삭제", -- Needs review
		["Delete profile:"] = "프로필 삭제", -- Needs review
		["Disable test mode"] = "테스트 모드 비활성화", -- Needs review
		["Enable test mode (need at least one visible nameplate)"] = "테스트 모드 활성화", -- Needs review
		General = "일반", -- Needs review
		["Icon size"] = "아이콘 크기", -- Needs review
		["Icon X-coord offset"] = "가로 위치", -- Needs review
		["Icon Y-coord offset"] = "세로 위치", -- Needs review
		MISC = "기타", -- Needs review
		["New spell has been added: %s"] = "새로운 주문이 추가되었습니다: %s", -- Needs review
		["Options are not available in combat!"] = "전투중에는 옵션을 활성화 시킬수 없습니다!", -- Needs review
		Profiles = "프로필", -- Needs review
		["Profile '%s' has been successfully deleted"] = "'%s' 의 데이터가 성공적으로 삭제되었습니다", -- Needs review
		["Show border around interrupts"] = "Show border around interrupts", -- Requires localization
		["Show border around trinkets"] = "Show border around trinkets", -- Requires localization
		["Unknown spell: %s"] = "알수없는 주문: '%s'", -- Needs review
		["Value must be a number"] = "값은 반드시 숫자로 입력되어야 합니다", -- Needs review
		["Font:"] = "Font:",
	},
	["zhCN"] = {
		["Always display CD icons at full opacity (ReloadUI is needed)"] = "Always display CD icons at full opacity (ReloadUI is needed)", -- Requires localization
		["Click on icon to enable/disable tracking"] = "点击图标启用/禁用跟踪", -- Needs review
		Copy = "复制", -- Needs review
		["Copy other profile to current profile:"] = "复制其他配置文件至当前配置文件：", -- Needs review
		["Current profile: [%s]"] = "当前配置文件： [%s]", -- Needs review
		["Data from '%s' has been successfully copied to '%s'"] = "从' %s'的数据已被成功复制到“%s”", -- Needs review
		Delete = "删除", -- Needs review
		["Delete profile:"] = "删除配置文件", -- Needs review
		["Disable test mode"] = "关闭测试模式", -- Needs review
		["Enable test mode (need at least one visible nameplate)"] = "启用测试模式（至少需要一个可见的姓名板）", -- Needs review
		General = "综合", -- Needs review
		["Icon size"] = "图标大小", -- Needs review
		["Icon X-coord offset"] = "图标的X坐标偏移", -- Needs review
		["Icon Y-coord offset"] = "图标的y坐标偏移", -- Needs review
		MISC = "杂项", -- Needs review
		["New spell has been added: %s"] = "New spell has been added: %s", -- Needs review
		["Options are not available in combat!"] = "选项不可用在战斗！", -- Needs review
		Profiles = "Profiles", -- Needs review
		["Profile '%s' has been successfully deleted"] = "Profile '%s' has been successfully deleted", -- Needs review
		["Show border around interrupts"] = "Show border around interrupts", -- Requires localization
		["Show border around trinkets"] = "Show border around trinkets", -- Requires localization
		["Unknown spell: %s"] = "未知的法术： %s", -- Needs review
		["Value must be a number"] = "值必须是数字", -- Needs review
		["Font:"] = "Font:",
	},
	["zhTW"] = {
		["Always display CD icons at full opacity (ReloadUI is needed)"] = "Always display CD icons at full opacity (ReloadUI is needed)", -- Requires localization
		["Click on icon to enable/disable tracking"] = "点击图标开启/关闭监视", -- Needs review
		Copy = "复制", -- Needs review
		["Copy other profile to current profile:"] = "将一个已保存的配置文件复制到当前配置文件:", -- Needs review
		["Current profile: [%s]"] = "当前配置文件: [%s]", -- Needs review
		["Data from '%s' has been successfully copied to '%s'"] = "已成功复制数据'%s'", -- Needs review
		Delete = "删除", -- Needs review
		["Delete profile:"] = "删除配置文件:", -- Needs review
		["Disable test mode"] = "关闭测试模式", -- Needs review
		["Enable test mode (need at least one visible nameplate)"] = "开启测试模式 （屏幕范围内要有至少一个姓名板）", -- Needs review
		General = "通用", -- Needs review
		["Icon size"] = "图标大小", -- Needs review
		["Icon X-coord offset"] = "X偏移量", -- Needs review
		["Icon Y-coord offset"] = "Y偏移量", -- Needs review
		MISC = "种族技能", -- Needs review
		["New spell has been added: %s"] = "已添加新的法术: %s", -- Needs review
		["Options are not available in combat!"] = "不能在战斗状态下进行设置！", -- Needs review
		Profiles = "配置文件", -- Needs review
		["Profile '%s' has been successfully deleted"] = "成功删除配置文件 '%s'", -- Needs review
		["Show border around interrupts"] = "Show border around interrupts", -- Requires localization
		["Show border around trinkets"] = "Show border around trinkets", -- Requires localization
		["Unknown spell: %s"] = "未知的法术: %s", -- Needs review
		["Value must be a number"] = "必须填写数字", -- Needs review
		["Font:"] = "Font:",
	},
	["ptBR"] = {
		["Always display CD icons at full opacity (ReloadUI is needed)"] = "Always display CD icons at full opacity (ReloadUI is needed)", -- Requires localization
		["Click on icon to enable/disable tracking"] = "Clique no ícone para ativar/desativar o rastreamento.", -- Needs review
		Copy = "Copiar", -- Needs review
		["Copy other profile to current profile:"] = "Copiar outro perfil para o perfil atual", -- Needs review
		["Current profile: [%s]"] = "Perfil atual", -- Needs review
		["Data from '%s' has been successfully copied to '%s'"] = "Dados de '%s' foram copiados para '%s' com sucesso ", -- Needs review
		Delete = "Deletar", -- Needs review
		["Delete profile:"] = "Deletar perfil", -- Needs review
		["Disable test mode"] = "Desativar modo de teste", -- Needs review
		["Enable test mode (need at least one visible nameplate)"] = "Ativar modo de teste (é necessário ao menos um nameplate visível) ", -- Needs review
		General = "Geral", -- Needs review
		["Icon size"] = "Tamanho do ícone", -- Needs review
		["Icon X-coord offset"] = "Coordenada X do Ícone", -- Needs review
		["Icon Y-coord offset"] = "Coordenada Y do Ícone", -- Needs review
		MISC = "Outros", -- Needs review
		["New spell has been added: %s"] = "Um novo feitiço foi adicionado.", -- Needs review
		["Options are not available in combat!"] = "Opções não estão disponíveis em combate!", -- Needs review
		Profiles = "Perfis", -- Needs review
		["Profile '%s' has been successfully deleted"] = "O perfil '%s' foi deletado com sucesso", -- Needs review
		["Show border around interrupts"] = "Show border around interrupts", -- Requires localization
		["Show border around trinkets"] = "Show border around trinkets", -- Requires localization
		["Unknown spell: %s"] = "Feitiço desconhecido", -- Needs review
		["Value must be a number"] = "Valor precisa ser um numero", -- Needs review
		["Font:"] = "Font:",
	},
	["itIT"] = {
		["Always display CD icons at full opacity (ReloadUI is needed)"] = "Visualizza le icone dei CD con l'opacità al 100%\r\n(è necessario ricaricare l'interfaccia utente)", -- Needs review
		["Click on icon to enable/disable tracking"] = "Clicca sull'icona per abilita/disabilitare il monitoraggio", -- Needs review
		Copy = "Copia", -- Needs review
		["Copy other profile to current profile:"] = "Copia un altro profilo nel profilo corrente", -- Needs review
		["Current profile: [%s]"] = "Profilo selezionato: [%s]", -- Needs review
		["Data from '%s' has been successfully copied to '%s'"] = "I dati da '%s' sono stati copiati con successo su '%s'", -- Needs review
		Delete = "Elimina", -- Needs review
		["Delete profile:"] = "Elimina profilo:", -- Needs review
		["Disable test mode"] = "Disabilita la modalità di test", -- Needs review
		["Enable test mode (need at least one visible nameplate)"] = "Abilita la modalità di test (è necessario visualizzare almeno un nameplate)", -- Needs review
		General = "Generale", -- Needs review
		["Icon size"] = "Grandezza delle icone", -- Needs review
		["Icon X-coord offset"] = "Coordinate di Offset X dell'icona", -- Needs review
		["Icon Y-coord offset"] = "Coordinate di Offset Y dell'icona", -- Needs review
		MISC = "MISC", -- Needs review
		["New spell has been added: %s"] = "Una nuova magia è stata aggiunta: %s", -- Needs review
		["Options are not available in combat!"] = "Non è possibile accedere alle opzioni in combattimento!", -- Needs review
		Profiles = "Profili", -- Needs review
		["Profile '%s' has been successfully deleted"] = "Il profilo '%s' è stato creato con successo", -- Needs review
		["Show border around interrupts"] = "Show border around interrupts", -- Requires localization
		["Show border around trinkets"] = "Show border around trinkets", -- Requires localization
		["Unknown spell: %s"] = "Magia sconosciuta: %s", -- Needs review
		["Value must be a number"] = "Il valore deve essere un numero", -- Needs review
		["Font:"] = "Font:",
	},
};

locales["koKR"] = locales["enUS"];
locales["zhCN"] = locales["enUS"];
locales["zhTW"] = locales["enUS"];

--			Test
locales["ruRU"] = locales["enUS"];
locales["deDE"] = locales["enUS"];
locales["esMX"] = locales["enUS"];
locales["frFR"] = locales["enUS"];
locales["esES"] = locales["enUS"];
locales["ptBR"] = locales["enUS"];
locales["itIT"] = locales["enUS"];

local localizedClasses = {};
FillLocalizedClassList(localizedClasses);
for _, localeTable in pairs(locales) do
	for classToken, localizedClassName in pairs(localizedClasses) do
		localeTable[classToken] = localizedClassName;
	end
end

local _, addonTable = ...;
addonTable.L = locales[GetLocale()];