local _, addonTable = ...;
local L = addonTable.L;

addonTable.DefaultSpells = {
	[51514] =	{ ["enabledState"] = "all", ["auraType"] = "buff/debuff", ["iconSize"] = 45 }, -- // Hex
	[6358] =	{ ["enabledState"] = "all", ["auraType"] = "buff/debuff", ["iconSize"] = 45 },
	[33786] =	{ ["enabledState"] = "all", ["auraType"] = "buff/debuff", ["iconSize"] = 45 },
	[5782] =	{ ["enabledState"] = "all", ["auraType"] = "buff/debuff", ["iconSize"] = 45 }, 
	[5484] =	{ ["enabledState"] = "all", ["auraType"] = "buff/debuff", ["iconSize"] = 45 }, 
	[45438] =	{ ["enabledState"] = "all", ["auraType"] = "buff/debuff", ["iconSize"] = 45 }, 
	[642] =		{ ["enabledState"] = "all", ["auraType"] = "buff/debuff", ["iconSize"] = 45 }, 
	[8122] =	{ ["enabledState"] = "all", ["auraType"] = "buff/debuff", ["iconSize"] = 45 }, 
	[23335] =	{ ["enabledState"] = "all", ["auraType"] = "buff/debuff", ["iconSize"] = 45 }, 
	[23333] =	{ ["enabledState"] = "all", ["auraType"] = "buff/debuff", ["iconSize"] = 45 }, 
	[34976] =	{ ["enabledState"] = "all", ["auraType"] = "buff/debuff", ["iconSize"] = 45 }, 
	[2094] =	{ ["enabledState"] = "all", ["auraType"] = "buff/debuff", ["iconSize"] = 45 }, 
	[33206] =	{ ["enabledState"] = "all", ["auraType"] = "buff/debuff", ["iconSize"] = 45 }, 
	[47585] =	{ ["enabledState"] = "all", ["auraType"] = "buff/debuff", ["iconSize"] = 45 }, 
	[87204] =	{ ["enabledState"] = "all", ["auraType"] = "buff/debuff", ["iconSize"] = 45 },
	[108416] =	{ ["enabledState"] = "all", ["auraType"] = "buff/debuff", ["iconSize"] = 45 }, 
	[104773] =	{ ["enabledState"] = "all", ["auraType"] = "buff/debuff", ["iconSize"] = 45 }, 
	[871] =		{ ["enabledState"] = "all", ["auraType"] = "buff/debuff", ["iconSize"] = 45 }, 
	[19263] =	{ ["enabledState"] = "all", ["auraType"] = "buff/debuff", ["iconSize"] = 45 }, 
	[61336] =	{ ["enabledState"] = "all", ["auraType"] = "buff/debuff", ["iconSize"] = 45 }, 
	[31230] =	{ ["enabledState"] = "all", ["auraType"] = "buff/debuff", ["iconSize"] = 45 }, 
	[6940] =	{ ["enabledState"] = "all", ["auraType"] = "buff/debuff", ["iconSize"] = 45 }, 
	[31821] =	{ ["enabledState"] = "all", ["auraType"] = "buff/debuff", ["iconSize"] = 45 }, 
	[48707] =	{ ["enabledState"] = "all", ["auraType"] = "buff/debuff", ["iconSize"] = 45 }, 
	[108271] =	{ ["enabledState"] = "all", ["auraType"] = "buff/debuff", ["iconSize"] = 45 }, 
	[53480] =	{ ["enabledState"] = "all", ["auraType"] = "buff/debuff", ["iconSize"] = 45 },
	[15286] =	{ ["enabledState"] = "all", ["auraType"] = "buff/debuff", ["iconSize"] = 45 }, 
	[122783] =	{ ["enabledState"] = "all", ["auraType"] = "buff/debuff", ["iconSize"] = 45 }, 
	[122278] =	{ ["enabledState"] = "all", ["auraType"] = "buff/debuff", ["iconSize"] = 45 },
	[115078] =	{ ["enabledState"] = "all", ["auraType"] = "buff/debuff", ["iconSize"] = 45 },
	[125174] =	{ ["enabledState"] = "all", ["auraType"] = "buff/debuff", ["iconSize"] = 45 },
};